#!/usr/bin/env python3
"""Export the social publishing queue into a WeChat mini program data module."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from course_audio_pipeline import repo_root


DEFAULT_SOURCE = Path("data/marketing/publish_queue_30d_ready.json")
DEFAULT_OUTPUT = Path("voiceHealth-miniprogram-v2/miniprogram/data/growthLaunchQueue.js")


def export_queue(source: Path, output: Path) -> int:
    data = json.loads((repo_root() / source).read_text(encoding="utf-8"))
    items = []
    for item in data["items"]:
        assets = item.get("assets", {})
        asset = assets.get("video") or assets.get("png") or ""
        items.append(
            {
                "id": item["id"],
                "day": f"D+{item['day']}",
                "channel": item["channel"],
                "time": item["scheduledTime"].split(" ", 1)[-1],
                "title": item["title"],
                "asset": Path(asset).name if asset else "",
                "caption": item["caption"],
                "tags": item.get("tags", []),
                "firstComment": item["firstComment"],
                "cta": item["cta"],
            }
        )

    target = repo_root() / output
    target.parent.mkdir(parents=True, exist_ok=True)
    content = "// Auto-generated by scripts/export_miniprogram_growth_queue.py\n"
    content += "module.exports = "
    content += json.dumps(items, ensure_ascii=False, indent=2)
    content += "\n"
    target.write_text(content, encoding="utf-8")
    return len(items)


def main() -> None:
    parser = argparse.ArgumentParser(description="Export growth launch queue to mini program JS.")
    parser.add_argument("--source", default=str(DEFAULT_SOURCE))
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()
    count = export_queue(Path(args.source), Path(args.output))
    print(json.dumps({"items": count, "output": args.output}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
